version: "3"
services:
  nextjs:
    build:
      container_name: tfpersuidev
      context: ./
      args:
        - APP_API_BASE_URL=http://20.205.128.164:5000
  nginx:
    build: ./nginx
    container_name: reverseproxy
    ports:
      - 80:80
