name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/tfpers/tfpers-ui:dev
          secrets: |
            "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}"
            "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}"
            "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
            "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}"
            "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
            "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}"
            "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            "BACKEND_URL=${{ secrets.BACKEND_URL }}"

      - name: Build nginx and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./nginx
          push: true
          tags: ghcr.io/tfpers/tfpers-nginx:dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to VM, build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
            sudo docker rmi ghcr.io/tfpers/tfpers-ui:dev
            sudo docker rmi ghcr.io/tfpers/tfpers-nginx:dev
            sudo docker pull ghcr.io/tfpers/tfpers-ui:dev
            sudo docker pull ghcr.io/tfpers/tfpers-nginx:dev
            cd FrontEnd
            sudo git checkout develop
            sudo git pull
            sudo docker-compose up -d --build
