name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/tfpers/tfpers-ui:dev

      - name: Build nginx and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./nginx
          push: true
          tags: ghcr.io/tfpers/tfpers-nginx:dev

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to VM, build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo echo ${{ secrets.GHCR_PASSWORD  }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            sudo docker pull ghcr.io/tfpers/tfpers-ui:dev
            sudo docker pull ghcr.io/tfpers/tfpers-nginx:dev
            cd FrontEnd
            sudo git pull
            sudo docker-compose up -d --build
